apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: openshift-auditd
objects:

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: openshift-auditd
    name: openshift-auditd
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: openshift-auditd:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/talset/openshift-auditd
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: centos:latest
      type: Docker
    triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0

- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: openshift-auditd
    name: centos
  spec:
    dockerImageRepository: "docker.io/library/centos"

- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: openshift-auditd
    name: openshift-auditd
  spec:
  status:
    dockerImageRepository: ""

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: openshift-auditd
  spec:
    selector:
      app: openshift-auditd
      deploymentconfig: openshift-auditd
    strategy:
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/container.openshift-auditd.image.entrypoint: '["/bin/bash"]'
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: openshift-auditd
          deploymentconfig: openshift-auditd
      spec:
        containers:
        - image: openshift-auditd:latest
          imagePullPolicy: Always
          name: openshift-auditd
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - openshift-auditd
        from:
          kind: ImageStreamTag
          name: openshift-auditd:latest
      type: ImageChange
